### ISSUE TITLE
how to finetune LLaMAX3

### ISSUE THREAD

**Issue by firdota** [CONE-MT/LLaMAX#1]
I tried llamax3 and it worked great.  I want to fine-tune this model using domain data. Can you share your training code?

Thanks.

**Comment by wowzero** [comment]
> I tried llamax3 and it worked great. I want to fine-tune this model using domain data. Can you share your training code?
> 
> Thanks.

Thank you for your interest in our work. LLaMAX is trained based on the LLaMA model, so any training framework that supports LLaMA can be directly used to fine-tune LLaMAX. For example, you can refer to the following Hugging Face training code: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py to continue pretrain LLaMAX on your own data. If you want to perform supervised fine-tuning on your own data based on LLaMAX, the following code will be useful: https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py 
Note that you may need to adjust the special tokens in lines 27-30 of the alpaca code to be compatible with LLaMA3-based models.

**Comment by firdota** [comment]
Thank you for your reply. I will close this issue.

> > I tried llamax3 and it worked great. I want to fine-tune this model using domain data. Can you share your training code?
> > Thanks.
> 
> Thank you for your interest in our work. LLaMAX is trained based on the LLaMA model, so any training framework that supports LLaMA can be directly used to fine-tune LLaMAX. For example, you can refer to the following Hugging Face training code: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py to continue pretrain LLaMAX on your own data. If you want to perform supervised fine-tuning on your own data based on LLaMAX, the following code will be useful: https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py Note that you may need to adjust the special tokens in lines 27-30 of the alpaca code to be compatible with LLaMA3-based models.
